### ISSUE TITLE
issue when trying to pip-install the `develop` branch

### ISSUE THREAD

**Issue by abehersan** [Jakob-Lass/DMCpy#87]
I tried cloning the repo, checking out to the `develop` branch to pip-install the soft. I am met with the following weird error:

```bash
(workenv) abehersan:DMCpy# pwd
/home/abehersan/github/DMCpy

(workenv) abehersan:DMCpy# git checkout develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.

(workenv) abehersan:DMCpy# pip install .
Processing /home/abehersan/github/DMCpy
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      /home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      /home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/dist.py:520: SetuptoolsDeprecationWarning: Invalid version: 'version=0.9.0'.
      !!

              ********************************************************************************
              The version specified is not a valid version according to PEP 440.
              This may not work as expected with newer versions of
              setuptools, pip, and PyPI.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************

      !!
        self._validate_version(self.metadata.version)
      running egg_info
      /home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/command/egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: 'version=0.9.0'.
      !!

              ********************************************************************************
              Version 'version=0.9.0' is not valid according to PEP 440.

              Please make sure to specify a valid version for your package.
              Also note that future releases of setuptools may halt the build process
              if an invalid version is given.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************

      !!
        return _normalization.best_effort_version(tagged)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/abehersan/github/DMCpy/setup.py", line 17, in <module>
          setup(
        File "/home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
          parsed_version = packaging.version.Version(self.egg_version)
        File "/home/abehersan/miniconda3/envs/workenv/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'version-0.9.0'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(workenv) abehersan:DMCpy#
```

Seems to be an issue with `setuptools.py` but I don't know for sure. Is there a workaround for this error @Jakob-Lass @oystesf ?

The most obvious solution would be to try and merge the develop with master if possible, since I have no issues pip-installing the `master` branch btw.

THNX,
Abraham

**Comment by Jakob-Lass** [comment]
Hi Abraham
I have not seen this deprecation warning before but might originate from a newer version of setuptools. What is your current version of setuptools and pip?

**Comment by Jakob-Lass** [comment]
I just discovered the culprit of the problem: With a newer version of setuptools, and combined with a typo from my side when generating the lastest version number ('version=0.9.0', which should simply be '0.9.0') the error occurs. Thus, if you remove the 'version=' part in setup.py or in the DMCpy folder run 'python make.py version 0.9.0', you should be good.
Hope this works

**Comment by abehersan** [comment]
Changing the typo in `setup.py` fixed it! Thnx a lot Jakob! (:

**Comment by oystesf** [comment]
Hi,I think this error originate from me. I think I did this when I made version 0.9.0 I used a wrong argument for the version number. It should be okay in 0.9.1.Are you installing 0.9.0? Best, Øystein 4. aug. 2023 18:15 skrev abehersan ***@***.***>:
Changing the typo in setup.py fixed it! Thnx a lot Jakob! (:
